### PR TITLE
Version 0.2.6

### LINKED ISSUE #23: Allow CSCPicker to set previously selected values
**Is your feature request related to a problem? Please describe.**
There's currently no way to tell the CSCPicker that it should contain previously selected values.

**Describe the solution you'd like**
`currentCountry`, `currentState`, and `currentCity` values

### PR DESCRIPTION
**Pull request by GroovinChip**
Closes #23 

* Introduce the `currentCountry`, `currentState`, and `currentCity` properties to allow previously selected values to remain
* Sort `CSCPicker` constructor first
* Move `super.initState` before other calls in `csc_picker.dart`
* Fix some typos, method names
* Fix some async method types

### CODE REVIEW

**Comment by GroovinChip** [comment]
@altafc22 any thoughts on this?

**Comment by altafc22** [comment]
Hey @GroovinChip, let me check the code, we will merge it soon

**Comment by ShehanAbid** [comment]
Hi, this version is not available in pubdev? i can only see 0.2.5 in there, and i need this feature. Can u please make it available on pubdev.

**Comment by altafc22** [comment]
Hi @ShehanAbid, tonight I will be available on pub.dev

Thank you.

**Comment by bipindubey-technoark** [comment]
Hii @altafc22 on pub.dev version 0.2.5 is showing.
I want features of 0.2.6 like currentstate and currentcountry how can we get it.

Thanks

**Pull request merged**
